// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnUZmZnGJb8-EcARjs_kDQAWq71yPscRU',
    appId: '1:448537975026:web:44b4c3f6df1f7ae6b0986b',
    messagingSenderId: '448537975026',
    projectId: 'bmi-app-dceeb',
    authDomain: 'bmi-app-dceeb.firebaseapp.com',
    storageBucket: 'bmi-app-dceeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPHQWMNiFzFJrD6EAD_rIrmJN0HVE9ww',
    appId: '1:448537975026:android:1de107599088354cb0986b',
    messagingSenderId: '448537975026',
    projectId: 'bmi-app-dceeb',
    storageBucket: 'bmi-app-dceeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2bTNHbKSfWlsNuZzLxnQcbElllkUkg8',
    appId: '1:448537975026:ios:bee7d7ddd8c67c40b0986b',
    messagingSenderId: '448537975026',
    projectId: 'bmi-app-dceeb',
    storageBucket: 'bmi-app-dceeb.appspot.com',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2bTNHbKSfWlsNuZzLxnQcbElllkUkg8',
    appId: '1:448537975026:ios:dd2da18a88ff2382b0986b',
    messagingSenderId: '448537975026',
    projectId: 'bmi-app-dceeb',
    storageBucket: 'bmi-app-dceeb.appspot.com',
    iosBundleId: 'com.example.bmiApp.RunnerTests',
  );
}
